ingress_public_hostname: larppikuvat.fi

postgres_managed: false
postgres_hostname: siilo.tracon.fi
postgres_database: larppikuvat
postgres_username: larppikuvat
postgres_ssl: true

redis_managed: false
redis_hostname: redis-ha-haproxy.redis-ha.svc.cluster.local
redis_broker_database: 5
redis_cache_database: 5

edegal_storage_pvc: false
edegal_storage_nfs_host: 91.105.252.80
edegal_storage_nfs_path: /opt/conikuvat/larppikuvat
edegal_secret_managed: false
edegal_admins:
- Luka Pajukanta <santtu@pajukanta.fi>

setup_should_run: true

smtp_server: sr1.pahaip.fi
smtp_default_from_email: root@tracon.fi

ingress_letsencrypt_enabled: true
ingress_letsencrypt_cluster_issuer: letsencrypt-prod

kompassi_editor_group: larppikuvat-staff
