ingress_public_hostname: conikuvat.fi

postgres_managed: false
postgres_hostname: siilo.tracon.fi
postgres_database: conikuvat
postgres_username: conikuvat
postgres_ssl: true

redis_managed: false
redis_hostname: redis-ha-haproxy.redis-ha.svc.cluster.local
redis_broker_database: 3
redis_cache_database: 3

edegal_storage_pvc: false
edegal_storage_nfs_host: 91.105.252.80
edegal_secret_managed: false
edegal_admins:
- Luka Pajukanta <santtu@pajukanta.fi>

setup_should_run: true

smtp_server: sr1.pahaip.fi
smtp_default_from_email: root@tracon.fi

ingress_letsencrypt_enabled: true
ingress_letsencrypt_cluster_issuer: letsencrypt-prod
